// .agents/skills/web-haptics/apps/vue-example/src/App.vue
<template>
  <div class="container">
    <button @click="trigger()">Tap me</button>
  </div>
</template>

<script setup lang="ts">
import { useWebHaptics } from "web-haptics/vue";

const { trigger } = useWebHaptics();
</script>

<style>
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  font-size: 2rem;
}
</style>

// .agents/skills/web-haptics/apps/react-example/src/App.tsx
import { useWebHaptics } from "web-haptics/react";

export default function App() {
  const { trigger } = useWebHaptics();

  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        height: "100vh",
        fontSize: "2rem",
      }}
    >
      <button onClick={() => trigger()}>Tap me</button>
    </div>
  );
}
