// .agents/skills/web-haptics/apps/svelte-example/src/App.svelte
<script lang="ts">
import { onDestroy } from "svelte";
import { createWebHaptics } from "web-haptics/svelte";

const { trigger, destroy } = createWebHaptics();
onDestroy(destroy);
</script>

<div class="container">
  <button on:click={() => trigger()}>Tap me</button>
</div>

<style>
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    font-size: 2rem;
  }
</style>

// .agents/skills/web-haptics/apps/vue-example/src/App.vue
<template>
  <div class="container">
    <button @click="trigger()">Tap me</button>
  </div>
</template>

<script setup lang="ts">
import { useWebHaptics } from "web-haptics/vue";

const { trigger } = useWebHaptics();
</script>

<style>
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  font-size: 2rem;
}
</style>
